[project]
name = "cari_custom"
authors = [
    {name = "Cari", email = "info@cari.local"},
]
dynamic = ["version"]
description = "Personel stok zimmeti, gunluk gorevlendirme ve kargo takibi ozel gelistirmeleri"
license = {file = "license.txt"}
requires-python = ">=3.10"
dependencies = [
    "frappe~=15.0.0",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]

[tool.ruff]
target-version = "py311"
line-length = 110

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "SIM", "C4", "EXE"]

[tool.ruff.format]
indent-style = "tab"
